# Test your FastAPI endpoints

### Homeworks
GET http://127.0.0.1:8000/homeworks
Accept: application/json


### Homework by id
GET http://127.0.0.1:8000/homeworks/1
Accept: application/json


### Simple solution
POST http://127.0.0.1:8000/solutions/1/auto
Accept: application/json
Content-Type: application/json

{ "content": "print('Hello world!')" }


### Simple solution no inputs
POST http://127.0.0.1:8000/solutions/13/auto
Accept: application/json
Content-Type: application/json

{ "content": "a = 5 \nb = 10 \n# your code here \nresult = a * b \nprint(result)" }


### Simple solution float inputs
POST http://127.0.0.1:8000/solutions/15/auto
Accept: application/json
Content-Type: application/json

{ "content": "a, b, c = map(float, input('Enter numbers a and b').split()) \n# your code here \nresult = a + b * ( c / 2 ) \nprint(f'Результат обчислення = {result}')" }







### Solution with string inputs
POST http://127.0.0.1:8000/solutions/5/auto
Accept: application/json
Content-Type: application/json

{ "content": "\ns = input()\nresult = ''.join(x.capitalize() for x in s.split('_'))\nprint(result)\n" }


### Function solution
POST http://127.0.0.1:8000/solutions/15/auto
Accept: application/json
Content-Type: application/json

{ "content": "\ndef solution(lst):\n    return max(lst) - min(lst)\n" }

