# Test your FastAPI endpoints

### Homeworks
GET http://127.0.0.1:8000/homeworks
Accept: application/json


### Homework by id
GET http://127.0.0.1:8000/homeworks/1
Accept: application/json


### Simple solution
POST http://127.0.0.1:8000/solutions/1/auto
Accept: application/json
Content-Type: application/json

{ "content": "print('Hello world!')" }


### Solution with no inputs
POST http://127.0.0.1:8000/solutions/13/auto
Accept: application/json
Content-Type: application/json

{ "content": "\na, b = 5, 10\nresult = a * b\nprint(result)" }


### Solution with float inputs
POST http://127.0.0.1:8000/solutions/15/auto
Accept: application/json
Content-Type: application/json

{ "content": "\na, b, c = map(float, input().split())\nresult = a + b * ( c / 2 )\nprint('Результат обчислення =', result)\n" }


### Solution with string inputs
POST http://127.0.0.1:8000/solutions/32/auto
Accept: application/json
Content-Type: application/json

{ "content": "\ns = input()\nresult = ''.join(x.capitalize() for x in s.split('_'))\nprint(result)\n" }


### Function solution
POST http://127.0.0.1:8000/solutions/115/auto
Accept: application/json
Content-Type: application/json

{ "content": "\ndef solution(lst):\n    return max(lst) - min(lst)\n" }

